library 'pipeline-library'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    preserveStashes(buildCount: 2)    
    skipDefaultCheckout true
    timeout(time: 10, unit: 'MINUTES')
  }
  triggers {
    eventTrigger jmespathQuery("image.action=='update' && image.name=='${baseImageName}'")
  }
  environment {
    REPO_OWNER = "${repoOwner}"
    REPO_NAME = "${repository}"
    GITHUB_CREDENTIAL_ID = "${githubCredentialId}"
  }
  stages {
    stage('Pull Request') {
      when {
        beforeAgent true
        anyOf {
          branch 'pr-*'
          triggeredBy 'EventTriggerCause'
        }
      }
      stages {
        stage('Build and Push Container Image') {
          steps {  
            echo "building and pushing container image for ${REPO_OWNER}/${REPO_NAME}"
            containerBuildPushGeneric(REPO_NAME) {
              checkout scm
              gitShortCommit()
            }
          }
        }
      }
    }
  }
}
