library 'cb-days@master'
def hugoPodYaml = libraryResource 'podtemplates/hugo/pod.yml'
def cloudRunYaml = libraryResource 'podtemplates/cloud-run.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages {
    stage('Preview environment') {
      agent {
        kubernetes {
          label 'hugo-builder'
          yaml hugoPodYaml
        }
      }
      when {
        beforeAgent true
        branch 'pr-*'
      }
      stages {
        stage("Build site") {
          steps {
            checkout scm
            container('hugo') {
              sh 'hugo -b http://${BRANCH_NAME}.blog.cb-sa.io'
              stash name: "public", includes: "public/*"
            }
          }
        }
        stage("Build and push image") {
          steps {
            kanikoBuildPushGeneric("${projectName}", "${BRANCH_NAME}", "${gcpProject}"){
              checkout scm
              dir("public") {
                unstash "public"
              }
            }
          }
        }
        stage("Deploy to preview env") {
          agent {
            kubernetes {
              label 'cloud-run'
              cloud 'cloud-run'
              yaml cloudRunYaml
            }
          }
          steps {
            container('gcp-sdk') {
              sh 'gcloud beta run deploy blog-${BRANCH_NAME} --image gcr.io/${gcpProject}/${projectName}:${BRANCH_NAME} --allow-unauthenticated --platform managed --region us-central1'
            }
          }
        }
      }
    }
    // stage('Build and Push Image') {
    //   when {
    //     beforeAgent true
    //     branch 'master'
    //   }
    //   steps {  
    //     echo "${repoOwner}"
    //     kanikoBuildPush(env.IMAGE_NAME, env.IMAGE_TAG, "${gcpProject}") {
    //       checkout scm
    //     }
    //   }
    //   post {
    //     success {
    //       echo "${JOB_NAME} pipeline job is awaiting approval at: ${RUN_DISPLAY_URL}"
    //     }
    //   }
    // }
    // stage('Deploy') {
    //   when {
    //     beforeAgent true
    //     branch 'master'
    //   }
    //   options {
    //     timeout(time: 90, unit: 'SECONDS') 
    //   }
    //   steps {
    //     input(message: "Should we deploy?", ok: "Deploy", submitterParameter: "APPROVER")
    //     kubeDeploy(env.IMAGE_NAME, env.IMAGE_TAG, "${githubCredentialId}", "${repoOwner}")
    //   }
    // }   
  }
}
