library 'cb-days@master'
def testPodYaml = libraryResource 'podtemplates/python/python-test-pod.yml'
pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages('Python Test and Build')
  {
    stage('Python Tests') {
      agent {
        kubernetes {
          label 'python'
          yaml testPodYaml
       }
      }
      steps {
        checkout scm
        gitShortCommit()
        stash name: "checkout", includes: "**/**"
        stash name: "k8s-deploy", includes: ".kubernetes/**"           
        container('python3') {
          sh '''
             pipenv install --system --user
             '''
        }
      } 
    }
    stage('Build and Push Image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps { 
        containerBuildPushGeneric("${repoOwner}/${repository}", "latest", "${gcpProject}")
        {
          unstash "checkout"
        }
      }
    }
    stage('Deploy') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps {
        blogBackendKubeDeploy("${repository}", "${repoOwner}", "gcr.io/${gcpProject}", "${deploymentDomain}") {
          unstash "k8s-deploy" 
        }
      }
    }
  }
}

